[package]
name = "server_actix_web"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
cargo-watch = "8.5.3"
derive_more = "2.0.1"
futures = "0.3.31"
serde = "1.0.227"
serde_json = "1.0.117"
serde_urlencoded = "0.7.0"
